# Sentiment Analysis: Kate's Seafood

Author: Megan Schaeb  
Date: 8/15/2023

## Load and Clean Data

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_excel("KatesReviews.xlsx")
data

,Unnamed: 0,reviewer_name,reviewer_loc,review_date,star_rating,review_text
0,Review 1,Ann P.,"South Dennis, MA",6/12/2023,5 star rating,A group of us enjoyed lunch today. Service was...
1,Review 2,K S.,"Newtown, CT",8/7/2023,1 star rating,Are you kidding me? Here we go with no real m...
2,Review 3,David S.,"San Francisco, CA",8/30/2022,4 star rating,Was back at Kate's for the 2nd time this summe...
3,Review 4,Lori G.,"Maricopa, AZ",6/7/2022,5 star rating,Kate's is open again this summer and they've u...
4,Review 5,Brittany K.,"San Francisco, CA",6/22/2021,5 star rating,"The clam strips were fantastic, Cape Cod Reube..."
...,...,...,...,...,...,...
119,Review 120,Jan A.,"South Salem, NY",9/14/2008,4 star rating,Window service. I have only every had the ice ...
120,Review 121,K. L.,"Trumbull, CT",8/19/2013,3 star rating,This place is OK but not the best ice cream. O...
121,Review 122,Brooke K.,"Woburn, MA",5/14/2012,5 star rating,"When my husband, who's been coming here for ye..."
122,Review 123,Tom H.,"Braintree, MA",9/1/2013,5 star rating,Hidden gem. Drive past this place for 10 year...
123,Review 124,Norma T.,"Eastham, MA",8/2/2013,1 star rating,Ordered the whole belly clam roll and it was t...

In [3]:
data.shape

(124, 6)

In [28]:
data2 = data.copy()
data2

,Unnamed: 0,reviewer_name,reviewer_loc,review_date,star_rating,review_text
0,Review 1,Ann P.,"South Dennis, MA",6/12/2023,5 star rating,A group of us enjoyed lunch today. Service was...
1,Review 2,K S.,"Newtown, CT",8/7/2023,1 star rating,Are you kidding me? Here we go with no real m...
2,Review 3,David S.,"San Francisco, CA",8/30/2022,4 star rating,Was back at Kate's for the 2nd time this summe...
3,Review 4,Lori G.,"Maricopa, AZ",6/7/2022,5 star rating,Kate's is open again this summer and they've u...
4,Review 5,Brittany K.,"San Francisco, CA",6/22/2021,5 star rating,"The clam strips were fantastic, Cape Cod Reube..."
...,...,...,...,...,...,...
119,Review 120,Jan A.,"South Salem, NY",9/14/2008,4 star rating,Window service. I have only every had the ice ...
120,Review 121,K. L.,"Trumbull, CT",8/19/2013,3 star rating,This place is OK but not the best ice cream. O...
121,Review 122,Brooke K.,"Woburn, MA",5/14/2012,5 star rating,"When my husband, who's been coming here for ye..."
122,Review 123,Tom H.,"Braintree, MA",9/1/2013,5 star rating,Hidden gem. Drive past this place for 10 year...
123,Review 124,Norma T.,"Eastham, MA",8/2/2013,1 star rating,Ordered the whole belly clam roll and it was t...

In [32]:
def get_city(loc):
    list_loc = loc.split(", ")
    city = pd.Series(list_loc[0])
    return city

def get_state(loc):
    list_loc = loc.split(", ")
    state = pd.Series(list_loc[1])
    return state

In [33]:
data2["reviewer_city"] = data2["reviewer_loc"].apply(lambda loc: get_city(loc))
data2["reviewer_state"] = data2["reviewer_loc"].apply(lambda loc: get_state(loc))
data2

,Unnamed: 0,reviewer_name,reviewer_loc,review_date,star_rating,review_text,city,state
0,Review 1,Ann P.,"South Dennis, MA",6/12/2023,5 star rating,A group of us enjoyed lunch today. Service was...,South Dennis,MA
1,Review 2,K S.,"Newtown, CT",8/7/2023,1 star rating,Are you kidding me? Here we go with no real m...,Newtown,CT
2,Review 3,David S.,"San Francisco, CA",8/30/2022,4 star rating,Was back at Kate's for the 2nd time this summe...,San Francisco,CA
3,Review 4,Lori G.,"Maricopa, AZ",6/7/2022,5 star rating,Kate's is open again this summer and they've u...,Maricopa,AZ
4,Review 5,Brittany K.,"San Francisco, CA",6/22/2021,5 star rating,"The clam strips were fantastic, Cape Cod Reube...",San Francisco,CA
...,...,...,...,...,...,...,...,...
119,Review 120,Jan A.,"South Salem, NY",9/14/2008,4 star rating,Window service. I have only every had the ice ...,South Salem,NY
120,Review 121,K. L.,"Trumbull, CT",8/19/2013,3 star rating,This place is OK but not the best ice cream. O...,Trumbull,CT
121,Review 122,Brooke K.,"Woburn, MA",5/14/2012,5 star rating,"When my husband, who's been coming here for ye...",Woburn,MA
122,Review 123,Tom H.,"Braintree, MA",9/1/2013,5 star rating,Hidden gem. Drive past this place for 10 year...,Braintree,MA
123,Review 124,Norma T.,"Eastham, MA",8/2/2013,1 star rating,Ordered the whole belly clam roll and it was t...,Eastham,MA

In [36]:
def convert_score(score):
    num_score = int(score.split(" ")[0])
    return num_score

In [37]:
data2["rating"] = data2["star_rating"].apply(lambda score: convert_score(score))
data2

,Unnamed: 0,reviewer_name,reviewer_loc,review_date,star_rating,review_text,city,state,rating
0,Review 1,Ann P.,"South Dennis, MA",6/12/2023,5 star rating,A group of us enjoyed lunch today. Service was...,South Dennis,MA,5
1,Review 2,K S.,"Newtown, CT",8/7/2023,1 star rating,Are you kidding me? Here we go with no real m...,Newtown,CT,1
2,Review 3,David S.,"San Francisco, CA",8/30/2022,4 star rating,Was back at Kate's for the 2nd time this summe...,San Francisco,CA,4
3,Review 4,Lori G.,"Maricopa, AZ",6/7/2022,5 star rating,Kate's is open again this summer and they've u...,Maricopa,AZ,5
4,Review 5,Brittany K.,"San Francisco, CA",6/22/2021,5 star rating,"The clam strips were fantastic, Cape Cod Reube...",San Francisco,CA,5
...,...,...,...,...,...,...,...,...,...
119,Review 120,Jan A.,"South Salem, NY",9/14/2008,4 star rating,Window service. I have only every had the ice ...,South Salem,NY,4
120,Review 121,K. L.,"Trumbull, CT",8/19/2013,3 star rating,This place is OK but not the best ice cream. O...,Trumbull,CT,3
121,Review 122,Brooke K.,"Woburn, MA",5/14/2012,5 star rating,"When my husband, who's been coming here for ye...",Woburn,MA,5
122,Review 123,Tom H.,"Braintree, MA",9/1/2013,5 star rating,Hidden gem. Drive past this place for 10 year...,Braintree,MA,5
123,Review 124,Norma T.,"Eastham, MA",8/2/2013,1 star rating,Ordered the whole belly clam roll and it was t...,Eastham,MA,1

In [39]:
# drop review number column
data2.drop('Unnamed: 0', axis=1, inplace=True)
data2

,reviewer_name,reviewer_loc,review_date,star_rating,review_text,city,state,rating
0,Ann P.,"South Dennis, MA",6/12/2023,5 star rating,A group of us enjoyed lunch today. Service was...,South Dennis,MA,5
1,K S.,"Newtown, CT",8/7/2023,1 star rating,Are you kidding me? Here we go with no real m...,Newtown,CT,1
2,David S.,"San Francisco, CA",8/30/2022,4 star rating,Was back at Kate's for the 2nd time this summe...,San Francisco,CA,4
3,Lori G.,"Maricopa, AZ",6/7/2022,5 star rating,Kate's is open again this summer and they've u...,Maricopa,AZ,5
4,Brittany K.,"San Francisco, CA",6/22/2021,5 star rating,"The clam strips were fantastic, Cape Cod Reube...",San Francisco,CA,5
...,...,...,...,...,...,...,...,...
119,Jan A.,"South Salem, NY",9/14/2008,4 star rating,Window service. I have only every had the ice ...,South Salem,NY,4
120,K. L.,"Trumbull, CT",8/19/2013,3 star rating,This place is OK but not the best ice cream. O...,Trumbull,CT,3
121,Brooke K.,"Woburn, MA",5/14/2012,5 star rating,"When my husband, who's been coming here for ye...",Woburn,MA,5
122,Tom H.,"Braintree, MA",9/1/2013,5 star rating,Hidden gem. Drive past this place for 10 year...,Braintree,MA,5
123,Norma T.,"Eastham, MA",8/2/2013,1 star rating,Ordered the whole belly clam roll and it was t...,Eastham,MA,1

In [40]:
# look for missing values in dataset
data2.isna().sum()

reviewer_name    0
reviewer_loc     0
review_date      0
star_rating      0
review_text      0
city             0
state            0
rating           0
dtype: int64

## Sentiment Analysis